steps:
  # Build the project GraalVM native image
  - name: 'vegardit/graalvm-maven:latest-java21'
    entrypoint: mvn
    args:
      - 'package'
      - '-Dpackaging=docker-native'
    env:
      - 'GCP_ID=$PROJECT_ID'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'REPO_HOSTNAME=$_REPOSITORY_HOSTNAME'
  # Upload the built image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$SHORT_SHA' ]
  # Deploy the built image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image=$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$SHORT_SHA'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--quiet'
substitutions:
  _REPOSITORY_HOSTNAME: europe-west1-docker.pkg.dev
