steps:
  # Build the project and push container image by maven JIB plugin
  - name: 'maven:3-eclipse-temurin-21'
    entrypoint: mvn
    args:
      - 'compile'
      - 'jib:build'
    env:
      - 'GCP_ID=$PROJECT_ID'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'REPO_HOSTNAME=$_REPOSITORY_HOSTNAME'
  # Deploy the built image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image=$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$SHORT_SHA'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--quiet'
substitutions:
  _REPOSITORY_HOSTNAME: europe-west1-docker.pkg.dev
